apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: route
  name: route
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: route
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: route
    spec:
      containers:
      - env:
        - name: MHS_DISABLE_SDS_TLS
          value: "True"
        - name: MHS_LOG_LEVEL
          value: NOTSET
        - name: MHS_SDS_REDIS_CACHE_HOST
          value: redis
        - name: MHS_SDS_REDIS_DISABLE_TLS
          value: "True"
        - name: MHS_SDS_SEARCH_BASE
          value: ou=services,o=nhs
        - name: MHS_SDS_URL
          value: ldap://192.168.128.11
        image: nhsdev/nia-mhs-route:0.0.2
        imagePullPolicy: ""
        name: route
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
